apiVersion: v1
kind: Secret
metadata:
    annotations:
        managed-by: argocd.argoproj.io
    labels:
        argocd.argoproj.io/secret-type: repository
    name: argo-github-repo-key
    namespace: argocd
data:
    #ENC[AES256_GCM,data:tvfJ9Q==,iv:Thw9q5keHQn1fqcl9bE5cucYbzFNj2izYCAcrFLoC5s=,tag:hD2TMq7Asejwlyd7Kapmhw==,type:comment]
    type: ENC[AES256_GCM,data:NPRW+Q==,iv:dwQSuISevGxqmqNIIeBK+BAeErMaXlPsxSXVNijufrQ=,tag:CkZzjlpr/y562K/oi1viDw==,type:str]
    #ENC[AES256_GCM,data:EVh8FVEJhvQU3g1HC93iERO+ut9aHJdWpXudI3sjPGP7xN3Jv+VQpm+6fE054tTrU4KOjDqXba0=,iv:Gjgl5lDr6kS/Su+mtOciqteBGJdWRHYT8lCChWCwfjQ=,tag:7DZEi9YNIKEpdTNgCNp5RQ==,type:comment]
    url: ENC[AES256_GCM,data:nGVEZQjMFyL6rdZdbU6OFBPuOnlOHvhBLI+XbiLXtZVN38wz+X3f8z7zsYcKJtGrNM4PVfTCbi+t5cp3OYubAgKEffrQvWQ5xoVw+g==,iv:Q7Jm+OHjZkwzvjhTqhsrzaOrqka3WAJW/X5cGwecljo=,tag:DK0Q2peiLbb2d3KA0iJGaw==,type:str]
    #ENC[AES256_GCM,data:Mrt7iMC+DNsoVrNhkRLSqA+V,iv:mex9C5DKvn293U20S7irsY880/Q72MhyFWVuwhoqbT8=,tag:T7e+gZUoTS5ETZq1rA+Y1w==,type:comment]
    username: ENC[AES256_GCM,data:RrOC8JhzBDSN+cll8LoouKwtUsCJGbI1,iv:BLc+3nO9JqCayAzwdN7QxbtMKS45F2sg97xHHAHR7zY=,tag:hD1cF7dA3IebIPjvimxP2g==,type:str]
    password: ENC[AES256_GCM,data:Ui1/RwFN4W0NrRBLRNH2qsmXmcSbjYLoMK4rXlkIN9bNxc60GnzYT59Kwzl8CwwhV3ysodnpASFcAVqZLmELPcK2Mk5+xGD0wMPDse0YksRRpDTzB04XRFCycdm7muVIa6b8+1Xl0hX7snslWf3sv125VVl2ZyxN6oA1ZQ==,iv:aNGgVsjKEwZlpUt90z7jygmBAcve4WV4IMs4JA0vuXA=,tag:58NGr7w/Cw2/v0uECWDd+g==,type:str]
    #ENC[AES256_GCM,data:kIUxyeE=,iv:tAoQR8FQwecnB4SXCC8kn50/+Z9QwoeUuchNrBnGZ80=,tag:ReWkBwswFPeQaQFKMCbMQw==,type:comment]
    forceHttpBasicAuth: ENC[AES256_GCM,data:TKwL2M96drY=,iv:UGI9s/2LUWi9O+B5HjS2xG2s0PvySNlP9AdEdKk2jjg=,tag:uS+YdFM19NnJLpCZ4cYWcQ==,type:str]
    #ENC[AES256_GCM,data:nyPcbH95IIVg4eM=,iv:UQZZWhMT/LEj0d746RnHgdSlQA2kVV/4F9WMO2xVmX0=,tag:Y87yE9QiT3Z1NJstmQyLzg==,type:comment]
    project: ENC[AES256_GCM,data:4DmnJ8CfeVIIlx0pzbbAIQ==,iv:sAJjrynkzCb4kB+cMHsRxbl2aa5qzBtEYPlNZuhZGIs=,tag:dIxthqKEwhZzKh1if13o9Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZWNrU1o1VW9nWXJPNlox
            bk8vanJic1gvZ1hBc2p1UmIrcWVsUjNLaUJjCnFRUEZQcXYvUWYyOUpkMWZlOGgz
            VnBCMWg1MWxPWWV0UkExOWdFNHovYnMKLS0tIE5RckRscmh0bHE3WkxyRHBhS3o0
            NHlqSHZaRjNwRFZHMWVtTytybk1xZU0KlznDe0tqHKK+I1bmCNXq3FUHzKyz1zQu
            0Nt6el43QUcNgT2GZSqZ8FmTmfElew19QEa+4VzoDNMMfLCWe1B2pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T22:55:27Z"
    mac: ENC[AES256_GCM,data:+khAdUwmElTbbULoro8g8CBgZLZKgM/AB6Nl/8MYtpgqs5/9o3LsdhuJkHpvkn5WpkQTPp//EMzkSIoRfphtFs5ScDbAjAf4GHU5QtU+JO99KiGW1YB8EKcsaP4u3sFzrsz7YaCUTmz/i/odhoWEKq7c7fZ8m/tnAPDr6e+DmQM=,iv:Qpthh+R46DZNYcKZ7XUnbgcBLcYZTHtmMfo3ytLizQ4=,tag:q0MkICgB8PbBEZXFMyTkNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# Repository credentials, for using the same credentials in multiple repositories.
apiVersion: v1
kind: Secret
metadata:
    name: argo-github-helm-oci-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    #ENC[AES256_GCM,data:tCSFEMU=,iv:V12UUqcdXaFVCLva7OJJT5l87i0Qh2lAfiFD8ybtQQc=,tag:jD0eEO/qLlaJhUk+S96F1g==,type:comment]
    type: ENC[AES256_GCM,data:bv4f76nYe8o=,iv:uUaZEusOs2osZyR22qyWWXEGgbBt+9Q2MYZXGyudLog=,tag:3N/0esmbUlYa7ggI4tOt9Q==,type:str]
    #ENC[AES256_GCM,data:D4AHpQsmHvlkaDiRi9CZZOEmBa+qGp6eaKNWX9cttrtc5RhSq9AR/nyTqoiP9Q==,iv:ddnO5g9vDVupMcoxnJnWMP0firegk2ykuJ0oMslLgI8=,tag:Zb9cJjLjm6fj3T9lRXiOgg==,type:comment]
    url: ENC[AES256_GCM,data:4lEhVCpLn6Buofs0U5fh848V2JxYycjoPiRCgxPyFtsxhbGeHcpvGhqhZGTjY3brN6woIXa/etL+RzRx,iv:uGdgNOWWmuQezQUYd+e8bVAx4xDacQWvjjEKcNQjHOc=,tag:++XsFCFw3Fd1dUDuVrtkBQ==,type:str]
    #ENC[AES256_GCM,data:rMLm41TRZ8H/ZtDY391MFHY9,iv:araATBniX6fWJuijkxYB6zPZXWZPv3BYbnVuU58NdM8=,tag:jZMTKHRr7vkUkzUhee2Cug==,type:comment]
    username: ENC[AES256_GCM,data:urEqSGqYHnaZGUTLe8z/6gCHX5zC5zWu,iv:1AvlhZ/hcqXMEOPql+Vz8o9hrz+VOa6W0LFS/LHOFSA=,tag:0KrqpAzmfPC62LxybxycpQ==,type:str]
    password: ENC[AES256_GCM,data:eAo/wvW2rnA05Mccwf7zwSeG0XMAmuVjdKc33e74kHVS7E3p1Yopfa49o3j3YtoER9DRJXZK1zy7WgV0iXHQz+8gBgtz0q5kpbj5ESvOrgHz9pNsOHS+ZbvoQVmMrMG1BaLuA3ZcexgigpkYwX0l/PWwFyHB02bJcOW9iA==,iv:U6/dhud4AZ4LFhJ71z+YeF38L0VLIWjyHSEuk9Lz6pw=,tag:2e+AphyAvMsLZjEfGq9Fog==,type:str]
    #ENC[AES256_GCM,data:AuyTz6X43Nj8+F8=,iv:5OD6vrJ32X9VjwvLn0xeVpkHHo+FNHC4tzX/L6G2RVU=,tag:8X8ZWLKLDqvNQg45YLLhjw==,type:comment]
    project: ENC[AES256_GCM,data:k+EhiUA3wxu8wLD5YrlURQ==,iv:YNFrnSF1VFPGdZWV/WMx1GF5xZEE2ZwgOkCLmJR4B1E=,tag:WfhCOsfA4Xf4zfxmczHC/Q==,type:str]
    #ENC[AES256_GCM,data:K5PuO4Q=,iv:z9nyzZeYcE+eL9X6uZ3mhyPGR/P5Px3rUCHASqv37kY=,tag:+jAGlRHT5ynBLudRz/I25A==,type:comment]
    enableOCI: ENC[AES256_GCM,data:kPU5P2k7rhE=,iv:g8QTf9myNaFdKU2q68vZVVqroDh4hRiVOmmcaqGK05I=,tag:fprArGv1cbBIU5uO+ufZOQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZWNrU1o1VW9nWXJPNlox
            bk8vanJic1gvZ1hBc2p1UmIrcWVsUjNLaUJjCnFRUEZQcXYvUWYyOUpkMWZlOGgz
            VnBCMWg1MWxPWWV0UkExOWdFNHovYnMKLS0tIE5RckRscmh0bHE3WkxyRHBhS3o0
            NHlqSHZaRjNwRFZHMWVtTytybk1xZU0KlznDe0tqHKK+I1bmCNXq3FUHzKyz1zQu
            0Nt6el43QUcNgT2GZSqZ8FmTmfElew19QEa+4VzoDNMMfLCWe1B2pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T22:55:27Z"
    mac: ENC[AES256_GCM,data:+khAdUwmElTbbULoro8g8CBgZLZKgM/AB6Nl/8MYtpgqs5/9o3LsdhuJkHpvkn5WpkQTPp//EMzkSIoRfphtFs5ScDbAjAf4GHU5QtU+JO99KiGW1YB8EKcsaP4u3sFzrsz7YaCUTmz/i/odhoWEKq7c7fZ8m/tnAPDr6e+DmQM=,iv:Qpthh+R46DZNYcKZ7XUnbgcBLcYZTHtmMfo3ytLizQ4=,tag:q0MkICgB8PbBEZXFMyTkNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# Repository credentials, for using the same credentials in multiple repositories.
apiVersion: v1
kind: Secret
metadata:
    name: argo-gitlab-helm-nooci-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    #ENC[AES256_GCM,data:yaESn6s=,iv:1ZGn3wtfDbnIjU0M4m1wNQ5aA+6Wz5NR9hqIyfyEa5M=,tag:uO5Zl3gMpYDs/omU1pKEdQ==,type:comment]
    type: ENC[AES256_GCM,data:fUnIMjsMFV8=,iv:xutSNG0qDdQhCJs5FPYBk1Q5HJfxTdjAGEZLXE/0bUU=,tag:JXJWpIA8ktvoVxPshiEMKw==,type:str]
    #ENC[AES256_GCM,data:ItBaEWNyEdgV7hka4Gv/DXykbaY2+HuRrMEFBuMIaYjGa/CVYGgPuw78/vAwMA==,iv:glxxCCukfAMt8KNfz1Kq55gVk8W8AKOyFdQepiayNNg=,tag:0kiH3dWWGcirgwBFlj9zfQ==,type:comment]
    url: ENC[AES256_GCM,data:K8PfArf0bT1G9KBld8FLNuO5g9n6DDGpoK1sWHUHJFrcYUNXE1C0vUeO9ThfmaH5JIoJ18+GrPuSBMjA,iv:n/2QEps593wf7ElnCp/+zJoZl1xU3CmNwSPPBX+KOh0=,tag:EmgbTj8EFgUXXW0Kre3Rag==,type:str]
    #ENC[AES256_GCM,data:M+IjV2M5tEWK5MmXMb4o83zQ,iv:yxmcAWaVItsxjUSx103EcN6sw13j088XNu+khnJK8cc=,tag:TOMO5Hpx8bEDBzpoofpczQ==,type:comment]
    username: ENC[AES256_GCM,data:+1x2jGAxUEpgV5HDoPFW4LnIB7Y2aUXn,iv:b8FfAHcdoIrsYbDcIOkV64TAe/+KfFso9QkCuFjhnT4=,tag:LlLSB7c9KRWAth79BiQneA==,type:str]
    password: ENC[AES256_GCM,data:KskXX135eWW/5f5Z8ij+xrp6GRrn9jiVBbREh5JqoTMr4avjlJ7OAMOMU0SVXdZoLECQiEj+carW4Sf/bLSyjn0IZVnDrip0jy8oWhsqeXfBBQRwsoedAKm64wQg7orqlXb6YAwfXntV4mV4XaFDIyXickBsX1ABbI00Vg==,iv:1Kj8pY/bWqoUUUc39yUiQxQ3bxKe53Ck5Wu0wyY2hbk=,tag:52BqNng5zrx/VfKdu6wo2A==,type:str]
    #ENC[AES256_GCM,data:eVssnSJoLpV+XbU=,iv:7Q3T1AQOajfellK4T5X+ehy1nt6v0WXevM6iDa4+ars=,tag:rqdVzr/eVlxtm9rjS5T92w==,type:comment]
    project: ENC[AES256_GCM,data:Vxgw/rYBLaSEustQKxqxaA==,iv:jPXI7JlaLwZBuUzxrovXfguy3/nCANaJCC7qoKcloTw=,tag:Wfi+hGbP50QmwFYQIoheOA==,type:str]
    #ENC[AES256_GCM,data:rKxWnLoT,iv:xyJdqZW3b78Fb0GAE4I6Ug13iHlBICr7uyHnDxDGBpI=,tag:uxUTx8Dy4m27+vig7CadhQ==,type:comment]
    enableOCI: ENC[AES256_GCM,data:8GJywfvkWCs=,iv:HvlliVvi3HU/MLOkk+bXwRzpY7NMsGeJ9UHNsc5zwLs=,tag:CJbCqTaV3pCQ3LhqJ9u3yQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZWNrU1o1VW9nWXJPNlox
            bk8vanJic1gvZ1hBc2p1UmIrcWVsUjNLaUJjCnFRUEZQcXYvUWYyOUpkMWZlOGgz
            VnBCMWg1MWxPWWV0UkExOWdFNHovYnMKLS0tIE5RckRscmh0bHE3WkxyRHBhS3o0
            NHlqSHZaRjNwRFZHMWVtTytybk1xZU0KlznDe0tqHKK+I1bmCNXq3FUHzKyz1zQu
            0Nt6el43QUcNgT2GZSqZ8FmTmfElew19QEa+4VzoDNMMfLCWe1B2pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T22:55:27Z"
    mac: ENC[AES256_GCM,data:+khAdUwmElTbbULoro8g8CBgZLZKgM/AB6Nl/8MYtpgqs5/9o3LsdhuJkHpvkn5WpkQTPp//EMzkSIoRfphtFs5ScDbAjAf4GHU5QtU+JO99KiGW1YB8EKcsaP4u3sFzrsz7YaCUTmz/i/odhoWEKq7c7fZ8m/tnAPDr6e+DmQM=,iv:Qpthh+R46DZNYcKZ7XUnbgcBLcYZTHtmMfo3ytLizQ4=,tag:q0MkICgB8PbBEZXFMyTkNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
