apiVersion: v1
kind: Secret
metadata:
    annotations:
        managed-by: argocd.argoproj.io
    labels:
        argocd.argoproj.io/secret-type: repository
    name: argocd-github-repo-key
    namespace: argocd
data:
    #ENC[AES256_GCM,data:urYHOw==,iv:aS33859plWvIOS4J0bfGc/ibemXumCCHJLdhK0Vzvg4=,tag:tJFpYGheOeRAlWhAL3osXA==,type:comment]
    type: ENC[AES256_GCM,data:XR6T1w==,iv:V0/N38Pp3asHQuoDqGX0eeRHWFSswo1ELrKG1ecKuHo=,tag:UHwXlwYK/d+H0F2kUCiZzg==,type:str]
    #ENC[AES256_GCM,data:YK0SgmZTM8SzqtafEYjTCYmkYnoJYr3RbHfZxpTT3Hr3dQPptBnaAyrJKDXKgFyArc9cfTs1JQo=,iv:iGzibD1w3ceDMvcmT0p77nCj07PfVIxvHxUzrwYA4rg=,tag:8ScvUn+0aIUnq5TrLnVK4w==,type:comment]
    url: ENC[AES256_GCM,data:V15t5Rnl05CXQAKLPUWlXOQjN+z9k9hO0FxKVcIxAevRMlTeCj0iRufDbaD3VnArpFQlCJyduI9ZPuvOdz66VUtpg91D2s1k+MfF1g==,iv:cDgwGayrL3ho/qxL1x6+2zAxxyxKrBUFmiEdC9ZYbFA=,tag:FHpbUaUHs0Ho4+zMAkJBAQ==,type:str]
    #ENC[AES256_GCM,data:S+Qu73xd8FnBqZu6zaUUuScd,iv:4iUuZ05DGLqwxZPyZt/JrU+gqavBif0ok+YbuBqG48M=,tag:3USZ+LmSw+U6BQu7Qeim7A==,type:comment]
    username: ENC[AES256_GCM,data:SeRP96kZNtlsVr2hciK6Xovif8o2LSu9,iv:cCTbiY9lyULnZxpNA4oTwkLgIxgaLbt+UOyVIAduino=,tag:xIJXo0mNAFxE4ezrtPjTqA==,type:str]
    password: ENC[AES256_GCM,data:I1WLxurC3TPXM56ag5dF8IuC/MRtKThPTEaPzp13q5pobgxGTholZAcURi8FEFI4zefSdte7HOKtwOuzb2MPjKWoOInmicVYRAGcbpc9L52xwPjjLU/BHk1UJEoagAMypJ5wBMMdQKEo2lQe3wfVO96HikzjyIX5neEPlQ==,iv:chEsb4tOT1nggAMs6C0rxAY+EctT8ztIjkxTF6U4zTw=,tag:QQjWKFY+IJWyae7BJeNA4w==,type:str]
    #ENC[AES256_GCM,data:xh8l48I=,iv:uMu2VCW9LA5bFm7oeiUDxZfl2fFe4fZXZBaTMDOP07w=,tag:tV1a7SPhzinE8grMVpkzfw==,type:comment]
    forceHttpBasicAuth: ENC[AES256_GCM,data:hQfxam0M9aA=,iv:4K3HTnwQcm+tub9BYfT8m7nCZvWHC1D66Lv/AX1LN1I=,tag:8IiFbnUCNi2eH4iAMVQJ2w==,type:str]
    #ENC[AES256_GCM,data:3fGcekD2KRvsQA4=,iv:R1mExmmX0bt1Ph+v05dO2NOzO49aSHalpsqKSbmpIvY=,tag:x4OeJzaU418L4GB4w+MjLw==,type:comment]
    project: ENC[AES256_GCM,data:bHy3mgRub5/Me4FKi/2u6A==,iv:UDpR3iLpG7xTnGceUUrfM/N6Ier6wR+Rg2gI0oLt4Fg=,tag:OP9XeC9KvJyI8SSK6JJpSQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVDk4LzNZZzk2aXdrMEc3
            a3RyRkw0czdzWk0zSUdYNlJ4aklGM0xnU25rCkFsVnp0T0h3aFk0SDNrN0pBNVJl
            MG9VeHhQbmF1STRqSHhxN3pzalh1S28KLS0tIEhjMnprQmdEZC9KWGhJK242ZXg4
            SVRiT0hLblo4VUNpbkk0QnBWWDE0RkEKZG4JKsJGJaHwVhKgY36KqpX+BWaGRNQt
            zj6DVlEg5IHBfr/pZyUWUe0zLy3LKkxMdIjWtdg06fmHZwPX5N/Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T09:37:23Z"
    mac: ENC[AES256_GCM,data:GWEuPKOEU4ANsCky6mQFOOj3RuoLQjGprvM/zHY9B7O5He06uotB+1Qn09A8z60zrrt+DiUbZG8KpZ4ceXBuYkWoqClE8T0cSQa+30s0l4rhifyzhwwchvpWaL9413cKUYv/pBlk4yrEWE/Eqq2NZzdorAd7bZyRoOKztZfmjSA=,iv:QcXwTHT/CjIOcPOlHrM1bzORVZhpWNweaRJfm/nvE2A=,tag:gZIh1WHuEuV1vYKi+OJnqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# Repository credentials, for using the same credentials in multiple repositories.
apiVersion: v1
kind: Secret
metadata:
    name: argocd-github-helm-oci-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    #ENC[AES256_GCM,data:Uk/3pmI=,iv:EDnjRl4bpnnY/rfub8EgdUl4cLIc42roV1w3QLiEPtA=,tag:8oGijtJlZ8lW7o4asHhOew==,type:comment]
    type: ENC[AES256_GCM,data:qKZXq1wMTo8=,iv:Qspdb2c+kpwHUthxIFBOQJPE7DcfsUYeGRzYjbVm2nQ=,tag:YeLIsy6kxaYnzacO8AeCPw==,type:str]
    #ENC[AES256_GCM,data:v8fCEtDOBgrCMIM4j0uDUm8X8zzlO/hn7b5abJZhB/kG+QRHB+PRZu5dnuYWzYu2,iv:iahsX4jZiKsqqJaQl/Gj1vlbaHVgsGbYY6QAIEUalps=,tag:gg1DDAyFUXqRJ/M9f+hNdQ==,type:comment]
    url: ENC[AES256_GCM,data:zBVu5UbS6Lq3m2ujpOTkiVbF4YjNYIA9qL4DjNN/rtp8FDQQgQkYT87xiukanKgGvIFJV5Xu8XISc/inkcveZQ==,iv:QCAOJAgQop5++R35tlf7c2DgHEQgxTb6Y9HUb69R5L8=,tag:Q4eWvqvgTNNd/OiV6Me37w==,type:str]
    #ENC[AES256_GCM,data:xUNcdaCztVo7qzg2guj4vXWM,iv:D0hMtAqzDgBcfQ1uK4jEgkc5V/LbwmIOfVHzA3Hfaz8=,tag:NyiPc6xny+mQQsOFZ1TDaA==,type:comment]
    username: ENC[AES256_GCM,data:in0ek1Gv/UnHEc6m3cNfyNEnsP6Dxu19,iv:ZpYDv5rQ+qNO6tBXpor/6Wysr226IID5tG5BznLhM1Q=,tag:ejF8ngOd8OZHB/KLj2/+DA==,type:str]
    password: ENC[AES256_GCM,data:tVDcfd9jj/ZPcQDn0Gk7Bbw8JI5+egrxnCP31yl4AIhaGNEefgdUpHDSQpx0q2VmZ/gqq/3L1HZXHscP3j4j4g9XFChI/GdqtcXewIjBq/LMYPcKkAY3ontVbz4AGqWw4m/uyECXMtJW7Q3I+1g/TER6qKqJiFSQJl/QXw==,iv:R5btuAnrvR4BFaY2N3TZBFeMZTeAMfTrmneLWZARCzk=,tag:sXYEVN6ANSBH7fJO+0f7aQ==,type:str]
    #ENC[AES256_GCM,data:NHGBJuMgG/To1Os=,iv:/WlR+uO5kYuVM9NMCcfzyJ4szq87Z0dXsF9EAUOt3oE=,tag:MowGd10biwYQM6APMj6DCg==,type:comment]
    project: ENC[AES256_GCM,data:yHXbKptD18ZREjcYvH1v5Q==,iv:zEM57/1EkUXyK9wXD5rUr8fJBEWxwaEPNrreqNTCSuQ=,tag:ydOT5zhlAhswlqinN3Iuqg==,type:str]
    #ENC[AES256_GCM,data:oiBRXA0=,iv:NXMqCYc6+RS1qH5au72iVuaSN0wXf0Oc0AWivSHLMKk=,tag:ggV9rXJE0EeakEqIRUyhMg==,type:comment]
    enableOCI: ENC[AES256_GCM,data:TQpQ1o/AZ+M=,iv:VsWQQ5FgNA/CNWUTH9atiKE+3wxEwNGugvvwzLZzIAo=,tag:AIInP+r8i/+cgaFtfJ204g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVDk4LzNZZzk2aXdrMEc3
            a3RyRkw0czdzWk0zSUdYNlJ4aklGM0xnU25rCkFsVnp0T0h3aFk0SDNrN0pBNVJl
            MG9VeHhQbmF1STRqSHhxN3pzalh1S28KLS0tIEhjMnprQmdEZC9KWGhJK242ZXg4
            SVRiT0hLblo4VUNpbkk0QnBWWDE0RkEKZG4JKsJGJaHwVhKgY36KqpX+BWaGRNQt
            zj6DVlEg5IHBfr/pZyUWUe0zLy3LKkxMdIjWtdg06fmHZwPX5N/Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T09:37:23Z"
    mac: ENC[AES256_GCM,data:GWEuPKOEU4ANsCky6mQFOOj3RuoLQjGprvM/zHY9B7O5He06uotB+1Qn09A8z60zrrt+DiUbZG8KpZ4ceXBuYkWoqClE8T0cSQa+30s0l4rhifyzhwwchvpWaL9413cKUYv/pBlk4yrEWE/Eqq2NZzdorAd7bZyRoOKztZfmjSA=,iv:QcXwTHT/CjIOcPOlHrM1bzORVZhpWNweaRJfm/nvE2A=,tag:gZIh1WHuEuV1vYKi+OJnqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# Repository credentials, for using the same credentials in multiple repositories.
apiVersion: v1
kind: Secret
metadata:
    name: argocd-gitlab-helm-nooci-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    #ENC[AES256_GCM,data:ZbX6N6Q=,iv:E4eC7crVRXs8KVnIohOuvYOCYG31QWI/8l6poAOttFU=,tag:412G2dqW+Tj+DOEosI9kAQ==,type:comment]
    type: ENC[AES256_GCM,data:rdijl7W0VJ4=,iv:i7CWE3rNlMDdSh3jqayl0KC1630BgzJsuMlW3d64FCs=,tag:TK28G0+uPSIx97htaj4bDg==,type:str]
    #ENC[AES256_GCM,data:rtmNiY23KLvsJAuB8JoiGCyfALKAxo/RxuPZl1Rd0nT5Y+jryUfjNtYYzPmWtN7v,iv:unHvu+r+bL3Lcke7r0X25Nb7Cq8GBzTAmtWCfK9tFYw=,tag:gjKw4ioPf1gNnDZgAe64Iw==,type:comment]
    url: ENC[AES256_GCM,data:2tLhyz334OGop+WzkROftKFNeUxAm4D5Q9WCpr+5XfuGoKF8UWrU9d7z2/v0Q6P3W2WTbD2yIfrgQIVh1cU9dA==,iv:nxmdAmYHfbxUmyLPBLd9LpHWu5gf8n2odntmQQcID+k=,tag:JVLdJQf2whZEIbN5SaIguw==,type:str]
    #ENC[AES256_GCM,data:8RpxmrMLHUKGc1ztJYD2WW6g,iv:oQeyT6rPiOrBqiaW84lAV6ype9vZXyq6Kq5EAWOvkWw=,tag:8GFp4+rPANywVEDjEFdByw==,type:comment]
    username: ENC[AES256_GCM,data:fo7csswUJdL7pgrpnnuGqKNXZoI/w4pU,iv:Y1lals1AVXZ+0eC9LeD/0qEpIUQFWlZtxpWiWyf/BvQ=,tag:9rFD6IQli/EfvhT8we6nWA==,type:str]
    password: ENC[AES256_GCM,data:NGZQmRScbzdK4kPXV7wLMU3UCO1KSGQFbx5WerXaxc4LDJiVp+WQvWmhcIV6j/6nJqJpIFaHVKoJnjBY58RjvDrvYjmYWksCB7EFK/7NTnjJTIos/UnqtdpRwulqDK0JnSBGl72Y9xXydMDNWqLQw6J5HqnOsOrRxhxsmg==,iv:soTggjGCJBFGnTmZLvOHd5rwrIj+e0gP0ckQaW1AJ1E=,tag:jVgnh4oqfZUMxyU1KDNTyg==,type:str]
    #ENC[AES256_GCM,data:+BA46znFk84yd1M=,iv:LlMuvjFDKj+6d3ErQJyogq2BD1bYomJ2uGYmVrAXMuk=,tag:s1Re+/qL3DLjgYQ/rjMEKA==,type:comment]
    project: ENC[AES256_GCM,data:QzBZFKA1HIDqCXvg1trGDw==,iv:ICk4Krr4tLQ45ZN8tKJtFvBD28+ib85FbCNGNUL6nAw=,tag:0pZ0w3cV0OB0LaGx3bXtcA==,type:str]
    #ENC[AES256_GCM,data:K75iC3zp,iv:dZlpxin856htfKRwrznEn0icZ14+ex3b/gp0HXi+fMo=,tag:AsMJYwbxoBBxQtZImy4lbA==,type:comment]
    enableOCI: ENC[AES256_GCM,data:ysnfy8IEJms=,iv:uV7N7JhEed7xN4+Su7BF4fJhXjvpXcGR4wIfZm431dQ=,tag:kp+8VjhZN8zgAYUvbR+c0w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVDk4LzNZZzk2aXdrMEc3
            a3RyRkw0czdzWk0zSUdYNlJ4aklGM0xnU25rCkFsVnp0T0h3aFk0SDNrN0pBNVJl
            MG9VeHhQbmF1STRqSHhxN3pzalh1S28KLS0tIEhjMnprQmdEZC9KWGhJK242ZXg4
            SVRiT0hLblo4VUNpbkk0QnBWWDE0RkEKZG4JKsJGJaHwVhKgY36KqpX+BWaGRNQt
            zj6DVlEg5IHBfr/pZyUWUe0zLy3LKkxMdIjWtdg06fmHZwPX5N/Vcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T09:37:23Z"
    mac: ENC[AES256_GCM,data:GWEuPKOEU4ANsCky6mQFOOj3RuoLQjGprvM/zHY9B7O5He06uotB+1Qn09A8z60zrrt+DiUbZG8KpZ4ceXBuYkWoqClE8T0cSQa+30s0l4rhifyzhwwchvpWaL9413cKUYv/pBlk4yrEWE/Eqq2NZzdorAd7bZyRoOKztZfmjSA=,iv:QcXwTHT/CjIOcPOlHrM1bzORVZhpWNweaRJfm/nvE2A=,tag:gZIh1WHuEuV1vYKi+OJnqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
