apiVersion: v1
kind: Secret
metadata:
    annotations:
        managed-by: argocd.argoproj.io
    labels:
        argocd.argoproj.io/secret-type: repository
    name: argocd-github-repo-key
    namespace: argocd
data:
    #ENC[AES256_GCM,data:zgkXrQ==,iv:DCj0aWH8ELQ2zXdcnnwMUW1qyE/5Jegi6UbOFnmUrI8=,tag:M5SXPF/bYJfJSgaBVNewuw==,type:comment]
    type: ENC[AES256_GCM,data:E/6L0w==,iv:8DBMZmqnm2NBc0EFfppI46avF/sAos32ayyQ+nxaVek=,tag:vRWgNHQNmVyHWNRfo5dUSA==,type:str]
    #ENC[AES256_GCM,data:ezqLdXiULMw89wBSzKFzdPv5fWUZyYuaxKTs0mWS0nz5PVYoa5rPBsv58l3V7kup6yxg689e07k=,iv:mxdIQle00PRP3UpRs3HPVYGL5lAHuGdVKcR3iAsgW9Y=,tag:PQUy2mHj9AmITfu9N0WilA==,type:comment]
    url: ENC[AES256_GCM,data:u8KoYvZJVK83Z6THCn6OL1aVjP0n27ZKQhVqx9YkEAMjUNGV6QxKPOSrMhk7CdwmGLpTQMB1OJcUJcCfrqutrUiDpTJUWjQAgIgfsQ==,iv:iA1MhR5OWZGEkr4Jb040s8KvHmWqL2h+s2/IruhdHXk=,tag:2PmvpxU1NUFUUl2GYXEbIQ==,type:str]
    #ENC[AES256_GCM,data:VGV/JsqIluGr7wSy66t9NpKE,iv:rbhgz2ym7fvfwJHUtyWw3W30M4DlAjgmQm1Dw6wCVNQ=,tag:B6a2NqTKZb7elTGGfj2PgA==,type:comment]
    username: ENC[AES256_GCM,data:qAUgwXs5XXLLG2cMXj05Bd0FErfDLEx7,iv:R42scwQwsEm2rYeS8bmyjcF9kQff629JUEJ04sw/CDs=,tag:cBBOopZz0lfnWxQHSzKyig==,type:str]
    password: ENC[AES256_GCM,data:D8SIUThMsMqRN9KGwTaOJ/DsYIrNDaZU6B48Mln2U7opoPFPCbVoobgfTX3CorA5YOWu8hYMGhGYdFu1cVHd5yHL6vf/sElLU55X2zqc/E6GcFhm5wVdfZJAmsODu+uQxreiNcVsCqC/455FvGx98bh/5+uA28V9Ch7wpw==,iv:733oY3gspjP6VMcBc2aSX6qTVzyQTPJ4tDD/N+bRQPk=,tag:DEZP6Gh5v4iR63yuoeVORw==,type:str]
    #ENC[AES256_GCM,data:YMBikbw=,iv:7rIAsioG/Rila5dchkfSWm0wAWH6qMmZ/64pC/qnmQk=,tag:Ceq3G2MCZcUyzukEgC0uPg==,type:comment]
    forceHttpBasicAuth: ENC[AES256_GCM,data:GbFHIsn7AR8=,iv:pPD7ueYS3faC0xCkxXzP4ylJDwQZCv/tADdtfxjKT3s=,tag:Zoz5OTGYFQk9RAlPISZAZQ==,type:str]
    #ENC[AES256_GCM,data:6OWi1uV06NjswC8=,iv:lqeGoA+9kflVrC3UE5SbbMMhyzTItW+6oOHA1weV4eY=,tag:jcdcJ22uaIl67POfKwpwEA==,type:comment]
    project: ENC[AES256_GCM,data:raP9Xxpxb/IVENRhZhlnIg==,iv:uTTED1eiEDIcv48Lu4hTsk9ADVymVbpV/HFFkERpVMc=,tag:Rul2tT+M+t1ok3kgF++2Cw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTlSMkRhS2JBMThyVkZG
            c0ZzRVprRFphcHdYNXdSSVhJSGJvb2YwYW5vCmZ3U0ZBQm9vczNvNWFBZEI2eG1T
            UnBNQkVnZWROa0ZSMEViejRLTHBsYzgKLS0tIHdwekwyTmtueDhmZVhKOVpvaVYr
            Zk9CRHUvOTh2UG43Wm1FVUNPNGpjZGsKQwM4ZL4nM1JVRxe/5Oh2FGReKf/Ow7nD
            28+3NiWSYAqsTa7WirZoF0MQ+G2Ed3CU5VWwfuj4dlZNVOFfX/5i9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T09:24:17Z"
    mac: ENC[AES256_GCM,data:BEwHk4mLgb1qkba3JpZdEXB2Go44oAcXjktZFoBxZe2sj4hOGmYxGVHDsh6ZMzVgbhqpcFJ8R3p0MlUfBVxYQT7wc87LWNs3bZ9ZJdJfPMu3Hbx9VtZB8z4G+o7X/iWJf7pnGkn0vHW2qWKFLsECTgSLKaoqb/1KFdU1uscvAmI=,iv:5RT0UudIjZ+FClWGsTKJ/GLjLHj3zdhK/nEPCl/E7+4=,tag:H+lUQ331Mn0773CTJiJz2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# Repository credentials, for using the same credentials in multiple repositories.
apiVersion: v1
kind: Secret
metadata:
    name: argocd-github-helm-oci-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    #ENC[AES256_GCM,data:s+ZWloY=,iv:vCSVJjJyATOFGawxVEMHXc/5zN7YY7LBeE3SbhUTJlY=,tag:Wde+cYGWF8+JBFxtEJ8iWA==,type:comment]
    type: ENC[AES256_GCM,data:lF+OTj/01Cw=,iv:G9vCrTjc/c6INg5RhMe3yrD5fcY5JwCTh3QY6P5MUfw=,tag:ARVoLgnRIaJXzwPHtFjR/w==,type:str]
    #ENC[AES256_GCM,data:ipSxT8kD/rkn0GvCy/cVQPkOPoU8XyHfa3ZcIzBhx3F0mLbwUo7DqL2D47cuHAV5,iv:znk1EmqhY7kzg3+E3uXXNsXrXlAHiyhfAhpRGyzzc7k=,tag:RuYZN6OnoQC5hzHWdTdUwg==,type:comment]
    url: ENC[AES256_GCM,data:uGXqxqBNJn5W5XdNSxGilzp7b+j/4axh8fRaxlmBO1J5s8FRwIz7OoLvv+6cLhNLVrHzdlzD4QaO7HDLEiHOmg==,iv:dFY9mCphE8hDHyrpbrIhZIrg7+sWAvni0HKtbbkBOiw=,tag:ngMmuv5oDH56kQcXh8PKDA==,type:str]
    #ENC[AES256_GCM,data:aphIsWORZrOAvNhSvotULotL,iv:zA/cI4OOjI0uS/z1PxUUNrLyNLqlHiMY6WXh0sk1iWk=,tag:a032ha1/49zCToP39c4hLg==,type:comment]
    username: ENC[AES256_GCM,data:6FZBOQFwA8+l33ljElsDQcdOOHXuum9X,iv:nFXNByWdNR/GBxnHzneUY6cFde6TCkjjYlsoqh22+9U=,tag:Ikga7BLwZZPAp9E31jvaxw==,type:str]
    password: ENC[AES256_GCM,data:OHQwUs59kdwSDKBuxM+9llqAnkcdywnpH9Y9XBtUkW+3V0kNYFMaZbfw+xjdovl+prtnDHs5r3/sKZ7Az9yNmW/N6P4F9yvMeHx8ERPPop0d6ZIUMLXlSaE9c18gIeWkLpJ9RKth5JeG2+uf2FWa2Kt24VZQKeatwkMkHA==,iv:jlx80vui5stxWKYefZQm2Y1/p8SD1R5/vEvhzt9iDJw=,tag:TR5PCNW0MDiB+IMMLQ8l/g==,type:str]
    #ENC[AES256_GCM,data:SrDPtE/yzS2+E7k=,iv:hglpOtUnOxGjgDtC4bpQyXquPSeh/kCOxGk+w4Aymrc=,tag:BMKD0MlWNGLtJ/0VL1Mc/g==,type:comment]
    project: ENC[AES256_GCM,data:QxcXkd3ZTL8lgqXw3wzFXg==,iv:GzsDY11lTbVjHslg9gIypn/xHpofzIgW3Q8JmtpNeKQ=,tag:pmIlJ/ItRGZGYawJJe7oHg==,type:str]
    #ENC[AES256_GCM,data:hXTFfGg=,iv:14FQLHk5yJfU8pB4KWUIGmmPDHUiXPYzO0d1zt5k2fw=,tag:XIRHFPBOJ9p8FffGcN4Pvg==,type:comment]
    enableOCI: ENC[AES256_GCM,data:2Z7xSTOsShw=,iv:dYoVVWrofF/QjBKMXYEnQXvf2KthUioB9gkQsiltnhI=,tag:96ZVM8bACwzdwKxc0ybrqw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTlSMkRhS2JBMThyVkZG
            c0ZzRVprRFphcHdYNXdSSVhJSGJvb2YwYW5vCmZ3U0ZBQm9vczNvNWFBZEI2eG1T
            UnBNQkVnZWROa0ZSMEViejRLTHBsYzgKLS0tIHdwekwyTmtueDhmZVhKOVpvaVYr
            Zk9CRHUvOTh2UG43Wm1FVUNPNGpjZGsKQwM4ZL4nM1JVRxe/5Oh2FGReKf/Ow7nD
            28+3NiWSYAqsTa7WirZoF0MQ+G2Ed3CU5VWwfuj4dlZNVOFfX/5i9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T09:24:17Z"
    mac: ENC[AES256_GCM,data:BEwHk4mLgb1qkba3JpZdEXB2Go44oAcXjktZFoBxZe2sj4hOGmYxGVHDsh6ZMzVgbhqpcFJ8R3p0MlUfBVxYQT7wc87LWNs3bZ9ZJdJfPMu3Hbx9VtZB8z4G+o7X/iWJf7pnGkn0vHW2qWKFLsECTgSLKaoqb/1KFdU1uscvAmI=,iv:5RT0UudIjZ+FClWGsTKJ/GLjLHj3zdhK/nEPCl/E7+4=,tag:H+lUQ331Mn0773CTJiJz2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
# Repository credentials, for using the same credentials in multiple repositories.
apiVersion: v1
kind: Secret
metadata:
    name: argocd-gitlab-helm-nooci-key
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
data:
    #ENC[AES256_GCM,data:Ik/UM8E=,iv:/1OJEw2IDXQJucMRNYuWVUBuoOoBGv5Hiud5S5PmeRM=,tag:uaKAjh8xlTGLUxQNTRcN6g==,type:comment]
    type: ENC[AES256_GCM,data:Ts2tZE/uGd4=,iv:WZMTpjdLtmC0NZD3H9NNbQZUMUXwIVklmDruk3nRzvE=,tag:YL3iyXJPLxbpIF8SUWE6/g==,type:str]
    #ENC[AES256_GCM,data:gHKMwPasm+E6kGf0IefXkmfE9UXnikpVZaXn5j+cu1Xss2YFx4novMK97DpbuNdM,iv:AfgWzIymVMDtN1IBaTQBXylAG+YO72GE5ObNnveOB3o=,tag:PH+oIkROFiM/0o0haFkx+w==,type:comment]
    url: ENC[AES256_GCM,data:DbFFMYLc0dNHqPunkyk+JaXa8dqvswg25A3Ux/h/htUHgWRFjoVAOwMvWDr4lTOdfgXJZ9O+8hz3J0Zk4MuqCg==,iv:peS/DqJF2YKSjkXooVFGlwX62aWrvc7mwL9H4koZTB0=,tag:gQW2lETvuSwlWJ/V6q+VFw==,type:str]
    #ENC[AES256_GCM,data:opTTvlj5GMfvP/zJ8SuQjQCL,iv:m/ne5Cpu1au0vks0x4Choec1D0+Tz6+rijcUNH9z3AM=,tag:T5wjEplrPScftKmlIlrGtQ==,type:comment]
    username: ENC[AES256_GCM,data:sllP4PXHGJBcp5EBg1l9pDF8X87jifm86zg=,iv:+59mY5myPi+BfmNlPhqjzIpj/AWPS3TmdXQgcrXV6/4=,tag:0pMOKetCqF3f/HzOJeTSaw==,type:str]
    password: ENC[AES256_GCM,data:bzY9piC7xctsAloFzPrJOXbQWZFzunPptoSOwktk0q6ahN37WTnqtWLhSilEVIjxinzlzBAK/RfP1KAszVDizSsCGRDV2x5VCISGTdRVTp1b0CPQhgozhSZxl2e/7lQEP2ELGdKZSteBN7XUI27Q1E8DfkJb3Cq0Su87Uw==,iv:1AFzHyGS5vXRgo9Rvuq6cGfoxyMe2q/umdflVOAnxMg=,tag:sMykeQj7nBjl9IuNT7k2NA==,type:str]
    #ENC[AES256_GCM,data:Ch3ep5SnaFpAFxw=,iv:j3xGprfZknsRYx2Y9wA4zpId9CPAxW+kerx0vpbKEuk=,tag:b/68VzkVmD4LGHh22hsHwQ==,type:comment]
    project: ENC[AES256_GCM,data:xJU7KYRN0HhVJJE01LQxHA==,iv:+SYW92NsPwE9EYC0Q1JsEpz/PXwyMbyiZ7PAreXkeZU=,tag:SA0e0JnN0PcNuY8PW4QCsQ==,type:str]
    #ENC[AES256_GCM,data:wgpzMRGL,iv:mf2GIterCkespVDazJHZoZMDDkeQ0gQRWIY1kTZbUUE=,tag:T9u6BslFhHqFGs9LSkqIKA==,type:comment]
    enableOCI: ENC[AES256_GCM,data:embihNxaLRM=,iv:mb18x0FWJYpre+TPq0GVApSk6v6cRdJ6hj7CreZCeyE=,tag:rMvOhpbHpcad5UAFMUg3IA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMTlSMkRhS2JBMThyVkZG
            c0ZzRVprRFphcHdYNXdSSVhJSGJvb2YwYW5vCmZ3U0ZBQm9vczNvNWFBZEI2eG1T
            UnBNQkVnZWROa0ZSMEViejRLTHBsYzgKLS0tIHdwekwyTmtueDhmZVhKOVpvaVYr
            Zk9CRHUvOTh2UG43Wm1FVUNPNGpjZGsKQwM4ZL4nM1JVRxe/5Oh2FGReKf/Ow7nD
            28+3NiWSYAqsTa7WirZoF0MQ+G2Ed3CU5VWwfuj4dlZNVOFfX/5i9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T09:24:17Z"
    mac: ENC[AES256_GCM,data:BEwHk4mLgb1qkba3JpZdEXB2Go44oAcXjktZFoBxZe2sj4hOGmYxGVHDsh6ZMzVgbhqpcFJ8R3p0MlUfBVxYQT7wc87LWNs3bZ9ZJdJfPMu3Hbx9VtZB8z4G+o7X/iWJf7pnGkn0vHW2qWKFLsECTgSLKaoqb/1KFdU1uscvAmI=,iv:5RT0UudIjZ+FClWGsTKJ/GLjLHj3zdhK/nEPCl/E7+4=,tag:H+lUQ331Mn0773CTJiJz2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
