apiVersion: v1
kind: Secret
metadata:
    name: controller-manager
    namespace: actions-runner-system
data:
    #ENC[AES256_GCM,data:BdUTkR4cxCICsLVUlWTui/JP,iv:CoaHcywrMnefOdsalmeaS7NuRbyzgG4v4PgVWXnWCr0=,tag:p8uJ0upgr/W3XhA7e0h9yQ==,type:comment]
    github_token: ENC[AES256_GCM,data:MVUBBqBDfSb8B0QtWZjvpQayZDSOKB+QVXWuENInnRZYT+Crw7+C/ASfFG6YQ5acDTwnO1E63uU=,iv:eHh+6DPlo3kdA9jRGixIlIdH4HcMR9hQ0i/bKLLGl+4=,tag:6Xr9/yk/DuCLZW/i8N2WCg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zp0safrpfcwyd4awf789mnl05alq0p5v05t4fza355r84k0rsphq8y9lpj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVi90eU5ReVI2RWVRRDZE
            c1pla21IYkhBWllTcjc3em81T3NwNXRvd1IwCkJqMUhMSmRQdzFLUkdMcWdzbzJ6
            em14bTlSUmhqbWRUd3VEc0l0ZWJsSHcKLS0tIFRVb1FCZnZkdjQwZnVXcDJJeStw
            dFZScE13SHdhVHRoNEhiazFDeXpNVW8KoSfmbqXvi2y7P8c+WufuoF1x+NHbBCZ+
            Or7LGv3jAYGiTrcjD3Z3Ea598FM37bfoJRtL5aCGu12IeIxsAxw5sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T07:00:42Z"
    mac: ENC[AES256_GCM,data:VqzNxY+qFtQM8/FQyWW5EE9HzbWECwtt01wdbHc6JWW5uwonL8EYrGS/mOc43fZoc8TO9Su6MexseAvl7o+WOuaPqh0qq1WU1fHYiNU3Xcz/+8f463L3BZjiKC2UXyZhOxotIHQf8uNmIwWjcpPuXWz2AAQioWf2rEYuGrNTQgU=,iv:aigAcPEwj96PEaiLNwj5x0UKo3Je+0Iy9khC8AIqs+A=,tag:sdjMRh10an+7Z3Zm1VqFzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
