---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Namespaces for the Cluster
# - namespaces/argocd.yaml
# - namespaces/argo-rollouts.yaml
# - namespaces/flux-system.yaml
# - namespaces/kyverno.yaml
# - namespaces/ingress-nginx.yaml
# - namespaces/actions-runner-system.yaml
# - namespaces/namespace-configuration-operator.yaml
# - namespaces/gatekeeper-system.yaml
# - namespaces/external-dns.yaml
# - namespaces/cert-manager.yaml
- namespaces/ns1.yaml
- namespaces/ns2.yaml

# Custom GitRepositories
- gitrepositories/fluxcd-deploy-feeder.yaml
# - gitrepositories/argo-bootstrap.yaml

# Custom HelmRepositories
- helmrepositories/fluxcd-helm-repo.yaml
- helmrepositories/podinfo.yaml
# - helmrepositories/ww-gitops.yaml
# - helmrepositories/ww-tf-controller.yaml
# - helmrepositories/kyverno.yaml
# - helmrepositories/flagger.yaml
# - helmrepositories/actions-runner-controller.yaml
# - helmrepositories/namespace-configuration-operator.yaml
# - helmrepositories/open-policy-agent-gatekeeper.yaml
# - helmrepositories/external-dns.yaml
# - helmrepositories/cert-manager.yaml
# - helmrepositories/secrets-store-csi-driver.yaml

# Custom Kustomizations
- kustomizations/secrets.yaml
# - kustomizations/argocd.yaml
# - kustomizations/argorollouts.yaml
# - kustomizations/argoworkflows.yaml
# - kustomizations/flamingo.yaml # Enable with cleanup of regular ArgoCD
# - kustomizations/app-deploy-ns1.yaml
# - kustomizations/app-deploy-ns2.yaml
# - kustomizations/ingress-nginx.yaml

# Custom HelmReleases
# - helmreleases/ww-gitops.yaml
# - helmreleases/ww-tf-controller.yaml
# - helmreleases/kyverno.yaml
# - helmreleases/flagger.yaml
# - helmreleases/actions-runner-controller.yaml
# - helmreleases/namespace-configuration-operator.yaml
# - helmreleases/open-policy-agent-gatekeeper.yaml
# - helmreleases/external-dns.yaml
# - helmreleases/cert-manager.yaml
# - helmreleases/secrets-store-csi-driver.yaml

# Custom Providers

# Custom Alerts
