---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 10m0s
  path: ./clusters/argo-kind-k8s/argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: argo-bootstrap
    namespace: flux-system
