---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy-kustomize/base/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-deploy
    namespace: flux-system