---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-age # kubectl create secret generic flux-sops-age --namespace=flux-system --from-file=age.agekey=/dev/stdin
  sourceRef:
    kind: GitRepository
    name: flux-system
  force: false
  interval: 10m0s
  path: ./clusters/flux-kind-k8s/flux-system/secrets
  prune: true
