---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-deploy
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: flux-github-repo-key
  url: https://github.com/yashwanth-l/fluxcd-deploy-feeder
