---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  url: https://open-policy-agent.github.io/gatekeeper/charts
  interval: 10m
