---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  interval: 10m
